#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__)) + '/../../config/boot'
rails_root = File.expand_path RAILS_ROOT
Dir.chdir(rails_root) # Change current directory to RAILS_ROOT
ENV['RAILS_ENV'] ||= "production"
require 'rubygems'
require "daemons"
require 'yaml'
require 'erb'

file_name = File.dirname(__FILE__) + "/../../vendor/rails/activesupport/lib/active_support.rb"

if(File.exists?(file_name))
  require file_name
else
  rails_version = File.new(File.dirname(__FILE__)+ "/../../config/environment.rb").read.scan(/^ *RAILS_GEM_VERSION.*=.*['|"](.*)['|"]/)[0].to_s
  gem 'activesupport', "="+rails_version
  require 'active_support'
end

options_file = File.dirname(__FILE__) + "/../../config/daemons.yml"
options = if File.exists?( options_file ) && File.readable?( options_file )
  YAML.load(
    ERB.new(
    IO.read(
    File.dirname(__FILE__) + "/../../config/daemons.yml"
    )).result).with_indifferent_access
else
  {
    :dir_mode => "script",
    :dir => "../../log",
    :multiple => false,
    :backtrace => true,
    :monitor => true
  }.with_indifferent_access
end
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run File.dirname(__FILE__) + '/daemonized_solr_processor.rb', options
